2024-12-09 15:16:45,345 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-40' coro=<TsharkXmlParser.get_packets_from_stream() done, defined at /home/archuser/Downloads/intrusion-detection-system-based-on-custom-rules/.venv/lib/python3.12/site-packages/pyshark/tshark/output_parser/tshark_xml.py:24> exception=EOFError()>
Traceback (most recent call last):
  File "/home/archuser/Downloads/intrusion-detection-system-based-on-custom-rules/main.py", line 74, in <module>
    menu.run()
  File "/home/archuser/Downloads/intrusion-detection-system-based-on-custom-rules/main.py", line 63, in run
    self.ids_system.start(verbose=verbose)
  File "/home/archuser/Downloads/intrusion-detection-system-based-on-custom-rules/main.py", line 21, in start
    self.traffic_monitor.start_capture(verbose=verbose)
  File "/home/archuser/Downloads/intrusion-detection-system-based-on-custom-rules/network_traffic_monitor/traffic_monitor.py", line 104, in start_capture
    for packet in capture.sniff_continuously():
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archuser/Downloads/intrusion-detection-system-based-on-custom-rules/.venv/lib/python3.12/site-packages/pyshark/capture/capture.py", line 221, in _packets_from_tshark_sync
    packet, data = self.eventloop.run_until_complete(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1948, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/archuser/Downloads/intrusion-detection-system-based-on-custom-rules/.venv/lib/python3.12/site-packages/pyshark/tshark/output_parser/tshark_xml.py", line 27, in get_packets_from_stream
    return await super().get_packets_from_stream(stream, existing_data, got_first_packet=got_first_packet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archuser/Downloads/intrusion-detection-system-based-on-custom-rules/.venv/lib/python3.12/site-packages/pyshark/tshark/output_parser/base_parser.py", line 22, in get_packets_from_stream
    raise EOFError()
EOFError
2024-12-09 15:17:34,411 - INFO - Packet #16: Protocol=UDP, Source=192.168.1.7, Destination=192.168.1.255, Length=92 bytes
